# Python CircleCI 2.1 configuration file
version: 2.1
jobs:
  build:
    environment:
      IMAGE_NAME: stalker
    docker:
      - image: circleci/python:2.7.16
    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: setup remote docker engine
      - setup_remote_docker
      # Step 3: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            pip install -r requirements.txt --user
      # Step 4: run tests
#      - run:
#          name: run tests
#          command: |
#            . venv/bin/activate
#            pytest -v --cov=scientific_calculator
      # Step 4: Build Docker Image
      - run:
          name: Build and Push Docker Image
          command: |
            docker build -t $IMAGE_NAME:latest .
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker tag $IMAGE_NAME $DOCKERHUB_USERNAME/$IMAGE_NAME:latest
            docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:latest
